export const NAV_LIST = [
  {
    name: 'V2',
    status: true,
    value: 0,
    url: '/vue2/#/energy',
    hash: '',
  },
  {
    name: 'R15',
    status: false,
    value: 1,
    url: '/react15#/react15',
  },
  {
    name: 'R16',
    status: false,
    value: 2,
    url: '/react16#/react16',
    hash: '',
  },
  {
    name: 'V3_首页',
    status: false,
    value: 4,
    url: '/vue3#/index',
    hash: '',
  },
  {
    name: 'V3_S',
    status: false,
    value: 3,
    url: '/vue3/#/select',
    hash: '',
  },
  // {
  //   name: '新车',
  //   status: false,
  //   value: 5,
  //   url: '/react16#/new-car',
  //   hash: '',
  // },
  // {
  //   name: '排行',
  //   status: false,
  //   value: 6,
  //   url: '/react16#/rank',
  //   hash: '',
  // },
]
